# -*- coding: utf-8 -*-
"""Mapping_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9KPjm5H0rBcYpTQLgou1hS7w0Qp4nJ3
"""

from google.colab import drive
drive.flush_and_unmount()
from google.colab import drive
drive.mount('/content/drive')
from unicodedata import numeric
from pathlib import Path
from google.colab import drive

import  pandas as pd
import re

from unicodedata import numeric
from pathlib import Path

BASE_DIR=Path().resolve().parent
GDRIVE_MOUNT=BASE_DIR/"gdrive"
DATA_DIR = GDRIVE_MOUNT / "/gdrive/My Drive/Classification_MLs/Nomb_fsp_Backend_TPO_Accounts"
drive.mount(GDRIVE_MOUNT.as_posix(), force_remount=True)

!ls /gdrive/MyDrive/Classification_MLs/Nomb_fsp_Backend_TPO_Accounts

tags = pd.read_excel(DATA_DIR/'Nomba_Accounts_Tags_Combined.xlsx')

# Create DataFrame
test_df = tags

# Mapping function
def map_investment(value):
    mapping_dict = dict(zip(test_df['reporting_tag'], test_df['mapping']))
    return mapping_dict.get(value, 'No mapping found')

# Apply the mapping function to the
test_df['mapped_value'] = test_df['reporting_tag'].apply(map_investment)


test_df

# Get unique values from the 'mapping' column.
unique_values = test_df['mapping'].unique()

# Create a new DataFrame from the unique values.
unique_df = pd.DataFrame({'unique_mapping': unique_values})

# Print the DataFrame.
unique_df